In [1]:
# import the necessary libraries
import numpy as np
import pandas as pd

# 1.Split string

In [2]:
name= "Hey I am Priyadarshan"
name.split()

['Hey', 'I', 'am', 'Priyadarshan']

# 2.Formatted string

In [3]:
#We can format string by Built in function .format method.

name="priyadarshan"
dept="IT"
print("Hi I am {name} from {dept}".format(name=name,dept=dept))

Hi I am priyadarshan from IT


# 3.Extract hello from nested dictionary

In [ ]:
nested_dictionary = {"k1":[1,2,3,
                   {"tricky":["oh","man","inception",
                              {"target":[1,2,3,"hello"]
                              }]}]
            }

print(nested_dictionary["k1"][3]["tricky"][3]["target"][3])

hello


# Numpy

## 4.1 Create an array of zeros

In [ ]:
numpy_12 = np.zeros(12)
numpy_12

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 5.Numpy array of all the even integers from 10 to 60

In [ ]:
np_even = np.arange(10,61,2)
np_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60])

## 6. Create a 3x3 matrix

In [ ]:
np_3d = np.arange(0,9).reshape(3,3)
np_3d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7.Concatenate two array

In [ ]:
num1 = np.array([1,2,3])
num2 = np.array([4,5,6])
concatenate = np.concatenate((num1, num2),axis=None)
concatenate

array([1, 2, 3, 4, 5, 6])

## 8.Create a dataframe with 3 rows and 2 columns

In [ ]:
rand_num = np.random.randint(10,size=(3,2))
df = pd.DataFrame(rand_num,columns=["row1","row2"])
df

row1  row2
0     9     0
1     5     5
2     8     5

In [ ]:
pd_dict = {
    "col_1":[1,2,3],
    "col_2":[2,5,6]
          }
# Create dataframe by dictionary
df = pd.DataFrame(pd_dict)
df

col_1  col_2
0      1      2
1      2      5
2      3      6

In [ ]:
# Add dataframe by list 
name_list = ["Vikram",20],["Vijay",20],["Surya",20],["Rolex",19]
df = pd.DataFrame(name_list,columns=["Name","Age"])
df

Name  Age
0  Vikram   20
1   Vijay   20
2   Surya   20
3   Rolex   19

## 9.Generate series of date from 1st jan 2023 - 10 th feb 2023

In [ ]:
# dataframe Generator 
df = pd.DataFrame()

df["time"] = pd.date_range(start ="1/1/2023",end ="2/10/2023",freq ="24H")

df["year"] =df["time"].dt.year
df["month"] = df["time"].dt.month
df["day"] = df["time"].dt.day

In [ ]:
df.head()

time  year  month  day
0 2023-01-01  2023      1    1
1 2023-01-02  2023      1    2
2 2023-01-03  2023      1    3
3 2023-01-04  2023      1    4
4 2023-01-05  2023      1    5

## 10. Create 2D list to dataframe

In [ ]:
list_2d = [[1,"aaa",22],[2,"bbb",25],[3,"ccc",24]]
df = pd.DataFrame(list_2d,columns=["col1","col2","col3"])
df

col1 col2  col3
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24